spring:
  application:
    name: state-machine-demo
  jpa:
    database: postgresql
    properties:
      org.hibernate.envers.revision_field_name: revision_id
      org.hibernate.envers.revision_type_field_name: revision_type
      jakarta:
        persistence:
          validation:
            mode: none
      hibernate:
        ddl-auto: validate
        default_schema: state_machine_demo
        current_session_context_class: org.springframework.orm.hibernate5.SpringSessionContext
  datasource:
    username: admin
    password: admin
    url: localhost:5432/customer_applications
    hikari:
      register-mbeans: true